ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "photoUrl" TEXT;
ALTER TABLE "Food" ADD COLUMN IF NOT EXISTS "ingredients" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TYPE "FoodSource" ADD VALUE IF NOT EXISTS 'FDC_API';
